In [13]:
import torch
import numpy as np

In [3]:
x = torch.empty(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.rand(2, 2, dtype=torch.float16)
print(x)

tensor([[0.7129, 0.5161],
        [0.1777, 0.3945]], dtype=torch.float16)


In [8]:
x.dtype

torch.float16

In [9]:
x.size()

torch.Size([2, 2])

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x / y
print(z)

z = torch.div(x,y)
z

tensor([[0.3280, 4.0785],
        [1.2013, 0.0799]])


tensor([[0.3280, 4.0785],
        [1.2013, 0.0799]])

In [19]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [20]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

It makes changes directly onto the original tensor

In [22]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [24]:
x = torch.rand(5, 3)
x

tensor([[0.8915, 0.2739, 0.3665],
        [0.9604, 0.9082, 0.0499],
        [0.2043, 0.9408, 0.3263],
        [0.3813, 0.5958, 0.5656],
        [0.5106, 0.4310, 0.2295]])

In [25]:
x[1,:]

tensor([0.9604, 0.9082, 0.0499])

In [26]:
x[:,1]

tensor([0.2739, 0.9082, 0.9408, 0.5958, 0.4310])

In [31]:
x = torch.randint(low=0, high=10, size=(5,3,3))
x

tensor([[[2, 7, 9],
         [6, 8, 3],
         [1, 4, 0]],

        [[7, 9, 8],
         [4, 0, 7],
         [8, 4, 3]],

        [[3, 6, 3],
         [8, 1, 7],
         [2, 2, 6]],

        [[1, 8, 3],
         [0, 2, 9],
         [1, 8, 7]],

        [[0, 4, 7],
         [8, 0, 3],
         [7, 9, 4]]])

In [ ]:
x[1,0,-1] + x[0,0,0] 

tensor(10)

In [40]:
x[1,1,1].item()

0

In [42]:
x[0,:,:]

tensor([[2, 7, 9],
        [6, 8, 3],
        [1, 4, 0]])

In [41]:
x[0,:,:].view(9)

tensor([2, 7, 9, 6, 8, 3, 1, 4, 0])

In [50]:
x[0,:,:].view(-1,3)

tensor([[2, 7, 9],
        [6, 8, 3],
        [1, 4, 0]])

In [52]:
a = np.ones(5)
b = torch.from_numpy(a)

In [54]:
y = x[0,:,:]
y.numpy()

array([[2, 7, 9],
       [6, 8, 3],
       [1, 4, 0]])

# Autogradient 

In [98]:
x = torch.rand(5, requires_grad=True)*10
x

tensor([6.9104, 7.1712, 0.5467, 0.0259, 2.1934], grad_fn=<MulBackward0>)

In [99]:
y = x + 2
y

tensor([8.9104, 9.1712, 2.5467, 2.0259, 4.1934], grad_fn=<AddBackward0>)

In [100]:
z = y*y*2
#z = z.mean()
z

tensor([158.7895, 168.2227,  12.9719,   8.2084,  35.1688],
       grad_fn=<MulBackward0>)

In [101]:
# We have to provide a direction, such that it's easy to compute the gradient.
# Becasue the Jacobian Matrix very expensive (m*n)
v = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0], dtype=torch.float32)
z.backward(v) #dz/dx

In [102]:
x.grad

/var/folders/6h/7_s8d7dn5p565dythb22sn0c0000gn/T/ipykernel_69714/3730140797.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/miniforge3/conda-bld/libtorch_1741997211379/work/build/aten/src/ATen/core/TensorBody.h:494.)
  x.grad


In [137]:
x = torch.tensor([2., 3.], requires_grad=True)
y = torch.tensor([1., 2.], requires_grad=True)   

z = x*y   # z is NOT a leaf
print(z)
v = torch.tensor([1.0, 0.0], dtype=torch.float32)
z.backward(v)
x.grad

tensor([2., 6.], grad_fn=<MulBackward0>)


tensor([1., 0.])

In [138]:
x = torch.tensor([2., 3.], requires_grad=True)
y = torch.tensor([1., 2.], requires_grad=True)   

z = x*y   # z is NOT a leaf
print(z)
v2 = torch.tensor([0.0, 1.0], dtype=torch.float32)
z.backward(v2)
x.grad

tensor([2., 6.], grad_fn=<MulBackward0>)


tensor([0., 2.])

In [142]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(5):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# Backpropagation

In [146]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad = True)

# Forward Pass
y_hat = w * x
loss = (y - y_hat)**2

print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [147]:
# Backward Pass

loss.backward()
print(w.grad)

tensor(-2.)


In [ ]:
# Update Weights


# Application

In [177]:
# f = 2 * x
X = np.array([1,2,3,4,5], dtype =np.float32)
Y = X*2

w = 0.0
learning_rate = 0.01

print(f"Prediction before training: f(6) = {np.dot(w,6)}")

# MSE = 1/N (Y-Y_hat)**2
# MSE = 1/N (Y-W*X)**2
def gradient(w, X, Y):
    # d/dw mean((w*X - Y)^2)
    return np.dot(2 * (w * X - Y), X) / X.size



for epoch in range(1000):
    y_hat  = np.dot(w,X)
    loss = ((Y - y_hat)**2).mean()
    
    dw = gradient(w, X, Y)
    w -= learning_rate * dw

    if epoch % 50 == 0:
        print(f"epoch {epoch}: w = {w:.3f}, loss = {loss:.5f}")

print(f"Prediction after training: f(6) = {np.dot(w,6)}")

Prediction before training: f(6) = 0.0
epoch 0: w = 0.440, loss = 44.00000
epoch 50: w = 2.000, loss = 0.00000
epoch 100: w = 2.000, loss = 0.00000
epoch 150: w = 2.000, loss = 0.00000
epoch 200: w = 2.000, loss = 0.00000
epoch 250: w = 2.000, loss = 0.00000
epoch 300: w = 2.000, loss = 0.00000
epoch 350: w = 2.000, loss = 0.00000
epoch 400: w = 2.000, loss = 0.00000
epoch 450: w = 2.000, loss = 0.00000
epoch 500: w = 2.000, loss = 0.00000
epoch 550: w = 2.000, loss = 0.00000
epoch 600: w = 2.000, loss = 0.00000
epoch 650: w = 2.000, loss = 0.00000
epoch 700: w = 2.000, loss = 0.00000
epoch 750: w = 2.000, loss = 0.00000
epoch 800: w = 2.000, loss = 0.00000
epoch 850: w = 2.000, loss = 0.00000
epoch 900: w = 2.000, loss = 0.00000
epoch 950: w = 2.000, loss = 0.00000
Prediction after training: f(6) = 11.999998569488525


In [179]:
# f = 2 * x
X = torch.tensor([1,2,3,4,5], dtype = torch.float32)
Y = X*2

w = torch.tensor(0.0, requires_grad = True)
learning_rate = 0.01

# MSE = 1/N (Y-Y_hat)**2
# MSE = 1/N (Y-W*X)**2
def forward(X):
    return w * X


def gradient(w, X, Y):
    # d/dw mean((w*X - Y)^2)
    return np.dot(2 * (w * X - Y), X) / X.size


print(f"Prediction before training: f(6) = {forward(6)}")


for epoch in range(1000):
    y_hat  = forward(X)
    loss = ((Y - y_hat)**2).mean()
    
    # Changing the gradient to use PyTorch
    #dw = gradient(w, X, Y)
    loss.backward()
    dw = w.grad

    #Tricky
    with torch.no_grad():
        w -= learning_rate * dw
    # zero gradient
    w.grad.zero_()

    
    if epoch % 50 == 0:
        print(f"epoch {epoch}: w = {w:.3f}, loss = {loss:.5f}")

print(f"Prediction after training: f(6) = {forward(6)}")

Prediction before training: f(6) = 0.0
epoch 0: w = 0.440, loss = 44.00000
epoch 50: w = 2.000, loss = 0.00000
epoch 100: w = 2.000, loss = 0.00000
epoch 150: w = 2.000, loss = 0.00000
epoch 200: w = 2.000, loss = 0.00000
epoch 250: w = 2.000, loss = 0.00000
epoch 300: w = 2.000, loss = 0.00000
epoch 350: w = 2.000, loss = 0.00000
epoch 400: w = 2.000, loss = 0.00000
epoch 450: w = 2.000, loss = 0.00000
epoch 500: w = 2.000, loss = 0.00000
epoch 550: w = 2.000, loss = 0.00000
epoch 600: w = 2.000, loss = 0.00000
epoch 650: w = 2.000, loss = 0.00000
epoch 700: w = 2.000, loss = 0.00000
epoch 750: w = 2.000, loss = 0.00000
epoch 800: w = 2.000, loss = 0.00000
epoch 850: w = 2.000, loss = 0.00000
epoch 900: w = 2.000, loss = 0.00000
epoch 950: w = 2.000, loss = 0.00000
Prediction after training: f(6) = 11.999998092651367
